spring:
  application:
    name: Generator
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    generate-ddl: true
    open-in-view: false


logging:
  level:
    org.springframework.security: TRACE

microservices:
  baseUrl: ${BASE_URL}

web:
  client:
    retry: 300
    max-attempts: 3
server:
  port: 19988